# Generated by Django 5.1.6 on 2025-03-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_initial'),
        ('patient', '0002_alter_patient_insurance_delete_insurancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insurancecompany'),
        ),
    ]
