# Generated by Django 5.1.6 on 2025-03-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_nextofkin_contacts_remove_patient_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='assigned_doctor',
        ),
    ]
