# Generated by Django 5.1.6 on 2025-03-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('ehr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronichealthrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='electronichealthrecord',
            name='vital_signs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
