# Generated by Django 5.1.6 on 2025-03-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('xray', 'X-Ray'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('blood_test', 'Blood Test'), ('other', 'Other')], max_length=20)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_performed', models.DateTimeField(blank=True, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('findings', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('radiology_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologytest')),
            ],
        ),
    ]
